# Project information
site_name: 'netID Developer Zone'
site_description: 'Developer Zone for netID, the european login standard of the European netID Foundation'
site_author: 'European netID Foundation'
site_url: 'https://eunid.github.io/netID-docs/'

# Theme Configuration
theme:
  name: 'material'
  language: 'en'
  font: 
    text: 'IBM Plex Sans'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  custom_dir: custom_theme/
  features:
    - tabs

# Github Repo
# repo_name: 'eunid/netID-docs'
# repo_url: 'https://github.com/eunid/netID-docs/'

# Site Navigation
nav:
    - About netID: index.md
    - Developer Portal:
        - Getting started: devportal/index.md
        - Tutorials:
            - Services: devportal/tutorial/services.md
            - Clients: devportal/tutorial/clients.md
            - User Management: devportal/tutorial/users.md
        - KPI Reports: devportal/reporting.md
    - Single Sign-on Integration: 
        - Technical Details: sso/index.md
        - Styleguide: sso/styleguide.md
        - Plugins: sso/plugins.md
    - CMP Integration:
        - General information: cmp/index.md
        - Browser-based API: cmp/browser-based.md
        - Server-based API: cmp/server-based.md
        - Export API: cmp/export.md
    - FAQ: faq.md

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: 1-3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

    
# PlantUML
plugins:
  - search
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/local/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # offical plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/diagrams" # should reside under docs_dir
      output_folder: "out"
      input_folder: "src"

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/netIDFoundation
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/enid


# Override CSS      
extra_css:
  - 'stylesheets/extra.css'

