@startuml

skinparam sequence {
	ArrowColor #76b82a
	ActorBorderColor #76b82a
    ActorBackgroundColor #FFF
	ActorFontColor #000
    ActorFontName Arial
	ActorFontSize 17

	LifeLineBorderColor #76b82a
	LifeLineBackgroundColor #76b82a
	
	ParticipantBorderColor #76b82a
	ParticipantBackgroundColor #76b82a
	ParticipantFontName Arial
	ParticipantFontSize 17
	ParticipantFontColor #FFF

}

autonumber "<b>[00]"
participant  "CMP JS" as cmp
participant  "Permission Layer" as pl
participant  "Read Service" as rs
participant  "Write Service" as ws

cmp -> cmp :  Check local/cached status \n Unknown user, no privacy status known
 group Check Status (privacy settings, user authentication)
    cmp -> rs : try to retrieve privacy status for authenticated user
    activate rs
    rs -> cmp : response - OK, CONSENT_REQUIRED, no privacy status present
    deactivate rs
    end
cmp -> cmp : Display CMP UI \n establish privacy status
Group Permantenly store privacy status with user account
cmp -> ws : store privacy status (TC String, netID Permission) via the WRITE SERVICE
activate ws
ws -> cmp : response: OK, TPID 
deactivate ws
end
cmp -> cmp : cache local status in netID Partner domain
@enduml